version: '3'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "C:\\Users\\vitor\\Área de Trabalho\\BlackOsint\\blackosint-frontend:/app"